api/v1alpha1/provider_types.go, config/crd/bases/notification.fluxcd.io_providers.yaml, docs/spec/v1alpha1/provider.md, internal/notifier/factory.go
Changes:
- Add the alert provider types to API
- Rename `webhook` alert provider to `generic`
=> Rename webhook alert provider to generic

config/manager/deployment.yaml
To allow alert rules for resources outside of the controller's
namespace.
=> Remove namespace scope from deployment

Dockerfile
This enables GitHub to link the container image to the repo.
=> Add opencontainers source label

api/v1beta1/provider_types.go, api/v1beta1/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/api/notification.md, docs/spec/v1beta1/provider.md, internal/notifier/client.go, internal/notifier/client_test.go, internal/notifier/discord.go, internal/notifier/discord_test.go, internal/notifier/factory.go, internal/notifier/forwarder.go, internal/notifier/forwarder_test.go, internal/notifier/rocket.go, internal/notifier/rocket_test.go, internal/notifier/slack.go, internal/notifier/slack_test.go, internal/notifier/teams.go, internal/notifier/teams_test.go, internal/server/event_handlers.go
Changes:
- Add `Proxy` optional field to Provider API
- Add URL prefix validation to CRDs
- Implement http(s) proxy for alerts
Proxy example:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
name: slack
namespace: default
spec:
type: slack
channel: general
address: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
proxy: https://proxy.corp:8080
```
Fix: #61
=> Add support for http(s) proxy when sending alerts

controllers/alert_controller.go, controllers/provider_controller.go, internal/server/event_handlers.go
Validate providers and alerts and report the validation errors in the status sub-resource.
Fix: #72
=> Add validation for providers and alerts

internal/notifier/util.go, internal/notifier/util_test.go
When I use the subgroup of gitlab I get an error "Incorrectly formatted git address"
the id on gitlab can use more than two block
I changed the code to be able to handle two or more blocks in the ID
Can you tell me if this is right for you?
=> Change code to use subgroup in gitlab

internal/notifier/bitbucket.go, internal/notifier/github.go, internal/notifier/github_test.go, internal/notifier/gitlab.go, internal/notifier/gitlab_test.go
The different git notifiers need repository ids in different formats.
On top of that some git providers support repositories in subgroups
while others do not support nesting. Each notifier needs test to verify
that they support their specific functionality.
=> Verify repository id in git notifiers

internal/notifier/bitbucket.go, internal/notifier/client.go, internal/notifier/client_test.go, internal/notifier/forwarder.go, internal/notifier/forwarder_test.go, internal/notifier/slack_test.go
Add support for sending a Notification-Controller header from the forwarder notifier.
This means that it can be identified in upstream requests.
=> Send notification header identify requests as coming from the notification component.

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta1/provider.md, go.mod, go.sum, internal/notifier/azure_devops.go, internal/notifier/azure_devops_test.go, internal/notifier/factory.go
Add Azure DevOps provider as the changes to the source-controller should now support Azure DevOps. After this we should have covered the major git providers out there that have a commit status api.
=> Add Azure DevOps provider

MAINTAINERS
See https://github.com/fluxcd/flux2/discussions/515.
=> Share flux2 maintainers

api/v1beta1/alert_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, docs/api/notification.md, docs/spec/v1beta1/alert.md, internal/server/event_handlers.go
Changes:
- Add summary (optional field) to Alert API 
- Add alert summary to notification metadata 
Example:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
name: ingress
namespace: nginx
spec:
summary: "Ingress traffic affected in production (us-west-2)"
providerRef: 
name: on-call-slack
eventSeverity: error
eventSources:
- kind: HelmRelease
name: nginx-ingress
```
Fix: #94
=> Add alert summary to notification metadata

docs/spec/v1beta1/provider.md
This adds an example of the `generic` webhook request for the Provider API.
Signed-off-by: Kevin McDermott <bigkevmcd@gmail.com>
=> Add example generic webhook request.

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/api/notification.md
When using a K8s `Secret` to store the webhook URL, the "address" data key has to be used. I know that this is mentioned in the docs and samples already, but when reading the spec first, this hint should improve clarity.
Please note if I missed anything.
=> Add hint about used "address" data key to the Provider CRD's SecretRef

controllers/alert_controller.go, controllers/provider_controller.go, go.mod, go.sum
To include a bug fix to the `ReconcilateAtChangedPredicate`
and renaming to `ReconcileRequestedPredicate`.
=> Upgrade runtime package to v0.6.2

api/v1beta1/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, config/rbac/role.yaml, controllers/receiver_controller.go, docs/spec/v1beta1/receiver.md, go.mod, go.sum, internal/server/receiver_handlers.go, main.go
Changes:
- Add `ImageRepository` to the Receiver API known kinds and RBAC
- Trigger container image updates to Git by annotating `ImageRepository` objects
- Add `ImageRepository` to the API usage examples
Ref: https://github.com/fluxcd/flux2/discussions/693
=> Trigger ImageRepository reconciliation with webhook receivers

api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/README.md, docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
This PR implements DockerHub webhook receivers, to be used for triggering container image updates.
Example:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
name: dockerhub-receiver
namespace: default
spec:
type: dockerhub
secretRef:
name: webhook-token
resources:
- kind: ImageRepository
name: webapp
```
=> Implement DockerHub webhook receiver

api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/README.md, docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
=> Add quay webhook

api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
=> Add GCR webhook receiver

internal/notifier/discord.go, internal/notifier/discord_test.go, internal/notifier/rocket.go, internal/notifier/rocket_test.go, internal/notifier/slack.go, internal/notifier/slack_test.go, internal/notifier/teams.go, internal/notifier/teams_test.go
This pull request adds the object kind of the source of the notification to the message.
The format is `<kind>/<name>.<namespaces>`
Fixes #120 
=> Add object kind to messages

api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
=> Add Nexus webhook receiver 

api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
=> Add generic webhook receiver for HMAC signing

api/v1beta1/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
This adds ImageUpdateAutomation and ImagePolicy as kinds allowed by cross-namespace
object references here. That has two effects:
- ImageUpdateAutomation and ImagePolicy objects can be the source of events; and,
- ImageUpdateAutomation and ImagePolicy objects can be the target of webhook
triggers.
Of these, the first is certainly desirable (e.g,. now you can post a Slack message when automation fails).
The second may be useful for ImageUpdateAutomation, though automations will more usually be triggered by ImageRepository objects changing; but in any case, doesn't hurt. It is not useful for ImagePolicy objects, but on balance, I think it's better to keep the type generic than to make a special case for ImagePolicy.
=> Allow ImageUpdateAutomations in object refs

docs/spec/v1beta1/receiver.md
Running the following command works on macOS (`LibreSSL 2.8.3`) but prints polluted output on Linux (`OpenSSL 1.1.1i  8 Dec 2020`)
```bash
printf '{}' | openssl dgst -sha1 -hmac "<secret-key>"
(macOS)> c75d9c41825117acf1f7a80b366fa1d47caf6962
(linux)> (stdin)= c75d9c41825117acf1f7a80b366fa1d47caf6962
```
The coreutils format output, with `-r`, adds `*stdin` at the end, removing it with `awk` make it works on both environments.
```bash
printf '{}' | openssl dgst -sha1 -r -hmac "<secret-key>" | awk '{print $1}'
(macOS)> c75d9c41825117acf1f7a80b366fa1d47caf6962
(linux)> c75d9c41825117acf1f7a80b366fa1d47caf6962
```
=> Fixing openssl oneliner to work on macOS and Linux

internal/server/event_handlers.go
=> Fix alerts regex filtering

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/google_chat.go, internal/notifier/google_chat_test.go
By essentially replicating the implementations for Teams and Slack a specific implementation for Google Chat has been developed and tested.
The are two points of note:
1. I've had to filter out 'Progressing' events as these seemed to replace the previous message within Google Chat. I couldn't easily find out why. However the output in chat is very similar to Discord so why this system does not display these messages is a mystery?
2. I've included the event timestamp as 'meta-data' within the message. Other implementation have not done this, so I'm happy to remove it for consistency sake if that is preferred.
Finally. I am not a Go developer, this is actually my first time coding in it. I like it, it's very clean. But I cut my teeth in C, C++, Java and beyond. So my apologies for any …
=> Provide the ability to send events to Google Chat

docs/spec/v1beta1/receiver.md, go.mod, go.sum, internal/server/receiver_handlers.go, main.go
=> Uses unstructured client to annotate object

internal/notifier/azure_devops.go, internal/notifier/azure_devops_test.go, internal/notifier/github.go, internal/notifier/github_test.go, internal/notifier/util.go
This change contains general fixes to the Azure DevOps notifier to fix smaller usability issues.
* Respect schema set by the provider url
* Modify the Azure DevOps notifier to allow compatibility with running behind a proxy.
* Check existing commit statuses to avoid spamming the same status when reconciling.
Signed-off-by: Philip Laine <philip.laine@xenit.se>
=> Fix Azure Devops notifier issues

docs/spec/v1beta1/provider.md
Fixes miss match between the docs and the actual code as mentioned in a discussion.
https://github.com/fluxcd/flux2/discussions/1089
=> Add missing provider types to docs

internal/server/event_handlers.go, internal/server/receiver_handlers.go
Use controller-runtime structured logging, required by: https://github.com/fluxcd/flux2/pull/1075
=> Use controller-runtime structured logging

controllers/alert_controller.go, controllers/receiver_controller.go, go.mod, go.sum
Part of https://github.com/fluxcd/flux2/issues/590
=> Record suspension metrics

internal/notifier/github.go, internal/notifier/github_test.go
Adds support for Github enterprise clients by checking the host of the url. If it is not github.com it is assumed that the enterprise client should be used.
Fixes #161
=> Add support for GitHub enterprise commit status

internal/notifier/google_chat.go
=> Remove filter for progressing events in googlechat

internal/notifier/bitbucket.go, internal/notifier/util.go, internal/notifier/util_test.go
Fixes #173 
Suggestion is to use sha1 sum as value.
Signed-off-by: Mikael Bergemalm <mbergemalm@gmail.com>
=> fix: use sha1 sum as value for key in bitbucket api requests

docs/spec/v1beta1/receiver.md
Adds a small note about the risks of exposing the receiver to the public internet and how to mitigate them.
Fixes #180
=> Add note about expoosing receiver to the internet

internal/server/event_handlers.go
Some errors like those from net/http will include the token value. We need to make sure that we redact the token value before logging as to not expose the value.
Fixes #160
=> Redact token from error log

internal/notifier/util.go, internal/notifier/util_test.go
This changes the parse revision logic to accept branches with slashes in them. Instead it will allow for infinite amount of slashes in the branch name and expect the last component to be the commit SHA.
Fixes #199
=> Fix revision parsing when branch contains slash

internal/notifier/factory.go, internal/notifier/slack.go, internal/notifier/slack_test.go
This change just brings the Slack provider inline with other providers which could be used with self hosted instances.
Fixes #203
=> Add cert pool to Slack provider requests

internal/notifier/client.go, internal/notifier/slack.go, internal/server/event_handlers.go
- Makes slack channel optional
- Only redacts token from logs if it is present (to prevent distorting the error message)
- Checks status code of HTTP request and returns an error if not successful
Fixes: #200 
=> Make slack channel optional

docs/spec/v1beta1/receiver.md
"Therefor" is a word, but I don't think this is one of its uses
Also `Kuberentes` -> `Kubernetes`
=> Fix a few typos

internal/notifier/sentry.go
With the current version, using the sentry provider, the notification controller panics when no custom certificates are set:
```
{"level":"info","ts":"2021-07-19T21:01:53.329Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-07-19T21:01:53.331Z","logger":"setup","msg":"starting event server","addr":":9090"}
{"level":"info","ts":"2021-07-19T21:01:53.331Z","logger":"setup","msg":"starting webhook receiver server","addr":":9292"}
{"level":"info","ts":"2021-07-19T21:01:53.332Z","logger":"setup","msg":"starting manager"}
I0719 21:01:53.332684       7 leaderelection.go:243] attempting to acquire leader lease flux-system/notification-controller-leader-election... …
```
=> providers/sentry: fix default HTTP Transport causing panic

docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/sentry.go, internal/notifier/sentry_test.go
use channel configuration for sentry environment to re-use the same DSN for multiple clusters
created this as a separate PR to not clash with the other sentry PR
=> providers/sentry: add environment support

docs/spec/v1beta1/provider.md, internal/notifier/sentry.go, internal/notifier/sentry_test.go
This is the last sentry PR, I promise 😄 
This PR adds support to send Sentry Traces instead of just errors. This means that normal info events are sent as traces and errors are sent as errors. 
This functionality can be disabled by setting `eventSeverity` in the related `Alert` object to `error`
=> providers/sentry: send traces

internal/server/receiver_handlers.go
This should prevent the generation of the object getting bumped, as
observed on a GKE K8s 1.18 cluster using the  logic before this commit.
We only want to generation to increase when there are actual changes to
the `spec` of a resource, as some controllers use the `generation`
value to make assumptions about what they should do during a
reconciliation.
Ref: https://github.com/fluxcd/helm-controller/issues/295
=> Request reconcile using patch instead of update

.github/workflows/e2e.yaml, api/v1beta1/alert_types.go, api/v1beta1/provider_types.go, api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, config/testdata/provider.yaml, config/testdata/status-defaults/alert.yaml, config/testdata/status-defaults/provider.yaml, config/testdata/status-defaults/receiver.yaml, docs/api/notification.md
This sets the `status.observedGeneration` field to -1 by default. This
is a follow-up to https://github.com/fluxcd/helm-controller/pull/294,
porting the same code to the notification-controller so that all Flux
2 controllers work the same way in this regard.
Signed-off-by: Max Jonas Werner <mail@makk.es>
=> feat: set default observedGeneration to -1 on CRDs

internal/notifier/alertmanager.go
=> Fix nil dereference err in AlertManager

api/go.mod, api/go.sum, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, go.sum
Fix https://github.com/fluxcd/flux2/pull/2277
=> Downgrade fluxcd/pkg/apis/meta to v0.10.2

docs/spec/v1beta1/provider.md, internal/notifier/alertmanager.go
Without the timestamp there is not enough entropy in the hash for
alertmanager to recongise that this is a new alert for some cases.
Adding the timestamp ensures that a new hash for the alert is created
each time and therefore no updates get missed.
=> Add timestamp as label for alertmanager

docs/spec/v1beta1/receiver.md
Closes: #230 
The Gitea webhooks work with the github receiver implementation. So this pull request just adds documentation.
=> Add documentation for gitea

.github/workflows/e2e.yaml, .gitignore, Makefile
Refactor logic to install helper tools into one function in th
Makefile. Add support for envtest to help install tools like kubectl,
etcd which helps users run tests more conveniently.
Ref: https://github.com/fluxcd/flux2/issues/2273
Signed-off-by: Sanskar Jaiswal <sanskar.jaiswal@weave.works>
=> Fix makefile envtest and controller-gen usage

.github/workflows/cifuzz.yaml, Makefile
Use the project specific smoke test to ensure the fuzzer correctness instead of using the official oss-fuzz GitHub action, which does not support well the multi-repository approach that FluxCD requires.
=> Replace cifuzz with custom smoke test

Dockerfile, config/manager/deployment.yaml
Further restricts the SecurityContext that the controller runs under, by enabling the default seccomp profile and dropping all linux capabilities.
This was set at container-level to ensure backwards compatibility with use cases in which sidecars are injected into the source-controller pod
without setting less restrictive settings.
Add a uid and gid for the container to enforce runAsNonRoot and ensure
the use of non root users.
BREAKING CHANGES:
1) The use of new seccomp API requires Kubernetes 1.19.
2) the controller container is now executed under 65534:65534 (userid:groupid).
This change may break deployments that hard-coded the user name 'controller' in their PodSecurityPolicy.
Ref: fluxcd/flux2#2014
Signed-off-by: Sanskar Jaiswal <sanskar.jaiswal@weave.works>
Co-authored-by: Paulo …
=> drop capabilities, enable seccomp and enforce runAsNonRoot

internal/notifier/factory.go, internal/notifier/matrix.go, tests/fuzz/matrix_fuzzer.go
This PR fixes #316 and allows using custom CA certificates with the Matrix provider.
=> Fix(Provider/Matrix): Load CA from CertSecretRef

.github/workflows/e2e.yaml, config/samples/notification_v1beta1_alert.yaml, config/samples/notification_v1beta1_provider.yaml, controllers/provider_controller.go, docs/spec/v1beta1/provider.md, go.mod, internal/notifier/factory.go, internal/notifier/forwarder.go, internal/notifier/forwarder_test.go, internal/server/event_handlers.go, tests/fuzz/forwarder_fuzzer.go
Closes: #312 
Supersedes: #291 
=> Pass headers to generic provider through secretRef

docs/spec/v1beta1/provider.md
Signed-off-by: Moshe Immerman <moshe@flanksource.com>
=> docs: update alert provider types

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/grafana.go, internal/notifier/grafana_test.go
Related to: https://github.com/fluxcd/flux2/issues/1024
This provider allows sending notifications to Grafana as annotations. To show the annotations on a dashboard there is a default tag (`flux`) that needs to be enabled.
Signed-off-by: Filipe Sequeira <filipe@weave.works>
=> Add support for Grafana annotations API

internal/notifier/discord.go
Fixes #323 
Changes: 
* username optional
* channel optional and remove it from payload
=> discord: Remove username and channel requirements

controllers/receiver_controller_test.go, internal/server/event_handlers.go, internal/server/receiver_handlers.go
=> Switch to controller-runtime metadata client

controllers/provider_controller.go, docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/grafana.go, internal/notifier/grafana_test.go, internal/notifier/util.go, internal/notifier/util_test.go, internal/server/event_handlers.go
Fix: #332 
Signed-off-by: Filipe Sequeira <filipe@weave.works>
=> Add basic auth support to grafana provider

api/v1beta1/alert_types.go, api/v1beta1/provider_types.go, api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
Status content could be very long compare to other fields. Moving it to
the end helps improve the visibility of other fields.
Ref: https://github.com/fluxcd/flux2/issues/2385
=> api: Move Status in CRD printcolumn to the end

config/manager/deployment.yaml
Ref: https://github.com/fluxcd/flux2/issues/2537
In https://github.com/fluxcd/source-controller/issues/284#issuecomment-774703153 it seems that leaving `fsGroup` unset can result in this error.
=> add fsgroup for securityContext

docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/webex.go, internal/notifier/webex_test.go, tests/fuzz/webex_fuzzer.go
Signed-off-by: ahothan <ahothan@cisco.com>
I have tested this against the latest webex API portal and verified I could get notifications in the targeted webex space.
Requires 2 additional parameters to make it work: a room ID and a Webex bot access token (both can be retrieved using the
webex developer web site after registering).
I have also enhanced the formatted markdown.
Example of webex space output:
=> Update the webex notification provider and markdown

internal/server/event_handlers.go, internal/server/event_handlers_test.go
=> Return err on invalid UTF-8 character in token

internal/notifier/alertmanager.go, internal/notifier/discord.go, internal/notifier/matrix.go, internal/notifier/opsgenie.go, internal/notifier/rocket.go, internal/notifier/slack.go, internal/notifier/teams.go, internal/notifier/webex.go
This pull request adds the error from parsing provider URLs to the returned error message.
This would be helpful in debugging issues and understanding why the URL might be invalid.
Ref: [discussion#2719](https://github.com/fluxcd/flux2/discussions/2719)
=> Better error messages for alert providers

go.mod, go.sum
This addresses CVE-2022-1996, due to v2.16.0 including
https://github.com/emicklei/go-restful/commit/926662532deb450272956c7bc573978464aae74e
and v3.8.0 including
https://github.com/emicklei/go-restful/commit/fd3c327a379ce08c68ef18765bdc925f5d9bad10
Trivy still detects a false positive due to an outdated database.
```
usr/local/bin/notification-controller (gobinary)
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 1)
┌────────────────────────────────┬───────────────┬──────────┬──────────────────────┬───────────────┬──────────────────────────────────────────────────────────────┐
│            Library             │ Vulnerability │ Severity │  Installed Version   │ Fixed Version │                            Title                             │ …
```
=> Force github.com/emicklei/go-restful to v2.16.0

internal/server/receiver_handler_test.go, internal/server/receiver_handlers.go
Closes #393 
The go-github library doesn't parse the `package` event probably due to some inconsistencies in what Github sends and differences in their API documentation.
Since we don't use the Go struct returned, this code has now been removed.
This pull request also adds tests for the receiver handler.
=> Remove code for parsing github payload

internal/server/event_handlers.go
This change fixes the cancel defer so that it is not cancelled before the go routine can run. The issue right now is that the Post function is cancelled prematurely. 
Fixes #406
=> Fix context cancel defer for commit status updates

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml
To solve discrepancies between parsing versus validation.
xref: https://github.com/kubernetes/apimachinery/issues/131
=> api: add custom validation for v1.Duration types

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/forwarder.go, internal/notifier/forwarder_test.go
This commit adds the "generic-hmac" Provider type for authenticating
webhook requests coming from notification-controller. I extended the
`Forwarder` notifier to accept an optional key used for generating the
HMAC. If the key is nil or empty no HMAC header is generated and the
forwarder behaves as before. If it is provided an `X-Signature` HTTP
header is added to the request carrying the HMAC.
I transformed the `TestForwarder_Post` test into a table-driven test
so that we can use the same setup and testing code for testing HMAC
and non-HMAC forwarder instances.
The Flux CLI will support this new type automatically as it doesn't validate the given type by itself (this is done by the API server using the CRD spec.
closes #99
=> Add "generic-hmac" Provider

api/v1beta2/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta2/providers.md, go.mod, go.sum, internal/notifier/factory.go, internal/notifier/gitea.go, internal/notifier/gitea_test.go
add support to send event notification to Gitea repo commit status
Gitea is a forge software package for hosting software development version control using Git as well as other collaborative features like bug tracking, code review, kanban boards, tickets, and wikis. It supports self-hosting but also provides a free public first-party instance
https://github.com/go-gitea/gitea
=> feat: add gitea notifier

api/v1beta2/provider_types.go, api/v1beta2/receiver_types.go, controllers/provider_controller.go, controllers/receiver_controller.go
The Kubernetes conversion webhook doesn't set the default value for the newly added `interval` field, to avoid controller panic, we set the default in code.
=> Fix panic when upgrading to v1beta2

controllers/suite_test.go, go.mod, go.sum
Set the default rate limiter configuration used in main.go in the test reconcilers as well.
Refer https://github.com/fluxcd/pkg/pull/443
=> Set rate limiter option in test reconcilers

api/v1beta2/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/api/notification.md, docs/spec/v1beta2/receivers.md, internal/server/receiver_handler_test.go, internal/server/receiver_handlers.go
At the moment one has to reference each resource by name for a webhook receiver.
While spec.resources actually is a `CrossNamespaceObjectReference` which supports matchLabels. However this is not implemented in the internal handling of the receiver.  What I like to achieve is basically trigger a reconcile for multiple HelmCharts matching a certain label (or just all of them in a specific namespace). 
This currently is unsupported in the reconcile logic while it is supported in the api:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
name: ghcr-receiver
namespace: flux-system
spec:
events:
- package
resources:
- apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
matchLabels:
registry: ghcr
name: '*'
secretRef:
name: github-webhook-token
type: …
```
=> feat: support multi receiver by matchLabels

api/v1beta2/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/api/notification.md, docs/spec/v1beta2/receivers.md
This has been introduced in #482 but we actually want this feature to only be available in v1 of the API. A follow-up PR will re-add this to the v1 API.
=> un-document receivers.spec.resources.matchLabels

api/v1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/api/v1/notification.md, internal/controllers/receiver_controller.go, internal/controllers/receiver_controller_test.go
Receiver `.status.url` was deprecated in v1beta2 API and replaced with `.status.webhookPath`. Remove it from v1 API and all references to it.
=> receiver/v1: Remove deprecated `.status.url` field

api/v1beta2/alert_types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, docs/api/v1beta2/notification.md, docs/spec/v1beta2/alerts.md, internal/controllers/alert_controller_test.go, internal/server/event_handlers.go
Fixes #512
Not sure if this is API `v1beta2` or `v1`.
=> Add InclusionList to Alert CRD

internal/controllers/receiver_controller.go, internal/controllers/receiver_controller_test.go, internal/server/receiver_handler_test.go, internal/server/receiver_handlers.go
Use `.status.webhookPath` as a key to index Receivers. Use this key while listing Receivers during the handling of a payload.
This enables us to list only the Receivers required instead of listing all the Receivers in the entire cluster.
=> index receivers using webhook path as key

api/v1beta2/alert_types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, docs/api/v1beta2/notification.md, docs/spec/v1beta2/alerts.md, internal/server/event_handlers.go
Fixes https://github.com/fluxcd/notification-controller/issues/511
=> Add event metadata field to Alert spec

internal/server/event_server.go, internal/server/event_server_test.go
Part of fixing https://github.com/fluxcd/helm-controller/issues/678
Supersedes https://github.com/fluxcd/notification-controller/pull/518
=> Include eventv1.MetaTokenKey on event rate limiting key calculation

internal/server/event_server.go
This to prevent collisions between different event attributes.
For example when first an event with revision `foo` is received without a token, after which a token `foo` is received without a revision.
Based on a thought exchange in https://github.com/fluxcd/helm-controller/pull/692#pullrequestreview-1441751192.
=> Prefix event key attributes with identifier

.github/dependabot.yaml, .github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yml, .github/workflows/scan.yml
Part of: https://github.com/fluxcd/flux2/issues/3709
=> Update workflows and enable dependabot

internal/server/event_handlers.go, internal/server/event_handlers_test.go, internal/server/event_server.go
As discussed [here](https://github.com/fluxcd/notification-controller/pull/543#discussion_r1221308513), it would be beneficial to have a logger on the request context of the Event Server containing the event's involved object's main metadata, i.e. kind, name and namespace, so that multiple places in the code logging this information don't need to create such verbose three-liner logger every time.
I'm also seizing the opportunity to remove a lot of repeated code for logging events about Provider objects in various places of the Event Handler code.
=> Reduce logging repeated code in event server

internal/notifier/gitea.go, internal/notifier/util.go
This change makes identifying the source of certain errors easier, e.g. in test failures or container logs.
=> Improve error messages in Gitea notifier

api/v1beta2/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta2/providers.md, go.mod, go.sum, internal/notifier/factory.go, internal/notifier/pagerduty.go, internal/notifier/pagerduty_fuzz_test.go, internal/notifier/pagerduty_test.go
This PR adds support for PagerDuty.
There are some assumptions made in regards to what should trigger an incident, I'm happy to be corrected on this.
It would be nice to allow Alerts to override some Provider settings e.g. override the channel (integration key) to send alerts to different PagerDuty integrations without needed to create a Provider for each.
=> Add support for PagerDuty

api/v1beta2/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/api/v1beta2/notification.md, docs/spec/v1beta2/providers.md
Addresses the discussion raised on #564 by @somtochiama.
I think this validation doesn't make sense anymore, as per this comment: https://github.com/fluxcd/notification-controller/pull/564#pullrequestreview-1501580895
=> Lift HTTP/S validation from Provider spec.address

internal/server/receiver_handlers.go
This pull requests updates the `handlePayload` function to use `strings.TrimPrefix` instead of `strings.TrimLeft`.
=> Use TrimPrefix instead of TrimLeft

api/v1beta2/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta2/providers.md, go.mod, go.sum, internal/notifier/datadog.go, internal/notifier/datadog_fuzz_test.go, internal/notifier/datadog_test.go, internal/notifier/factory.go, internal/notifier/util.go
This PR adds support for DataDog as a notification provider.
This provider publishes events that look like this:
...given a provider config that looks like this:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
name: datadog
namespace: flux-system
spec:
secretRef:
name: datadog-secret
type: datadog
address: https://api.datadoghq.com
channel: my-k8s-cluster-name
```
...and a secret that looks like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: datadog-secret
namespace: flux-system
stringData:
token: "datadog-api-key"
headers: |
my-custom-tag: tag-value
```
...and an alert that looks like this:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
name: datadog-info
namespace: flux-system
spec:
eventSeverity: info …
```
=> feat: add DataDog notification provider

docs/spec/v1beta1/README.md
This change fixes the documentation links for the notification manager APIs.
=> Fix README.md links to notification APIs

api/v1beta2/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta2/providers.md, go.mod, go.sum, internal/notifier/bitbucketserver.go, internal/notifier/bitbucketserver_test.go, internal/notifier/factory.go
Atlassian Bitbucket product offers multiple hosting options as documented [here](https://bitbucket.org/product/guides/getting-started/overview#bitbucket-software-hosting-options) 
For Flux users that use Bitbucket server or Bitbucket data center solution(mostly enterprises), there is no provider to support posting Git Commit Statuses. This PR provides the git commit status functionality for Bitbucket Server/Data Center.
[ Note: The reason that we can't use existing `bitbucket` provider and the need for a new `bitbucketserver` provider stems from the fact that the [REST API used by Bitbucket Server/Data Center](https://developer.atlassian.com/server/bitbucket/rest/v815/intro/#about) product is different from [Bitbucket Cloud REST API](https://developer.atlassian.com/cloud/bitbucket/rest/int …
=> Add Bitbucket server/Bitbucket Data Center provider for git commit status

api/v1beta3/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta3/providers.md, go.mod, go.sum, internal/notifier/factory.go, internal/notifier/nats.go, internal/notifier/nats_test.go
Fixes https://github.com/fluxcd/notification-controller/issues/470
Adds support to send events to a NATS subject. Supports authentication through Username/Password as well.
Due the similarities in architecture with Google Pub/Sub, I drew inspiration for the implementation and testing of this change from that provider.
=> Add Provider for NATS Subject

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Replacement of https://github.com/fluxcd/notification-controller/pull/661, avoiding rebasing `release/v1.2.x` branch to keep the tagged commit history.
=> Merge release/v1.2.x changes to main

go.mod, go.sum, internal/notifier/util.go
We discovered a vulnerability on the module `github.com/whilp/git-urls` [GHSA-3f2q-6294-fmq5](https://github.com/advisories/GHSA-3f2q-6294-fmq5). This repository doesn't look to be maintained at this moment. That is why we decided to fix the vulnerability and move the repository over our organization. We plan to maintain this repository in the future.
=> Replace whilp/git-urls module by chainguard-dev/git-urls

.github/dependabot.yaml
This package updates with controller-runtime
=> dependabot: Ignore `go-logr` package

.github/workflows/backport.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yml
Workflow dependency update backports were failing for some time. Update all the workflow dependencies in release/v1.2.x branch based on the latest from the main branch.
Closes https://github.com/fluxcd/notification-controller/pull/697
=> [release/v1.2.x] Backport workflows dependency updates from the main branch

api/v1/receiver_types.go, api/v1beta1/alert_types.go, api/v1beta1/provider_types.go, api/v1beta1/receiver_types.go, api/v1beta2/alert_types.go, api/v1beta2/provider_types.go, api/v1beta2/receiver_types.go, api/v1beta3/alert_types.go, api/v1beta3/provider_types.go
This tag isn't used by controller-tools, only `nonNamespaced` is.
Context: https://cloud-native.slack.com/archives/CLAJ40HV3/p1708794732147909
Tested by running `make generate` and verifying that there is no diff.
=> Remove `genclient:Namespaced` tag

internal/notifier/telegram.go
Current implementation was missing '*' symbol.
Fixes #734
Not sure how to test message parsing, because it is implemented on the server side.
=> Fix Telegram MarkdownV2 escaping

internal/notifier/opsgenie.go, internal/notifier/opsgenie_test.go
Add severity to opsgenie alerts to better be able to handle the opening and closing of alerts.
Related to #460
=> Add severity to opsgenie alerts

docs/spec/v1beta2/providers.md, docs/spec/v1beta3/providers.md, internal/notifier/bitbucketserver.go, internal/notifier/bitbucketserver_test.go
Add support for Bitbucket Context path
Fix: #742
=> Add support for Bitbucket Context path

docs/spec/v1beta3/providers.md, internal/notifier/alertmanager.go
notification-controller posted all outgoing Alertmanager alerts with "timestamp" label, effectively preventing grouping alerts related to the same resource and forcing users to configure a separate alert receiver with `send_resolved: false`.
This changes it to instead set "startsAt", which was previously set (automatically by Alertmanager) to alert posting time. "endsAt" remains unset, as we have no way of figuring that out but the reconciliation interval of the resource that generated the alert, which can currently only be found out by making a Kubernetes API round-trip.
Note that this requires users to adapt alert templates that relied on .Labels.Timestamp.
Fixes #793.
=> Alertmanager: Change timestamp label to .StartsAt

internal/notifier/telegram.go, internal/notifier/telegram_test.go
Hi, I saw the telegram notifier wont escape with metadata key. The key sometimes will need to be `kubernetes.io/somekey`. I think the escape for metadata key is needed.
=> telegram notifier should escape with metadata key

.github/workflows/scan.yml
Automated backport to release/v1.3.x, triggered by a label in https://github.com/fluxcd/notification-controller/pull/866.
Conflicts resolved manually.
=> [release/v1.3.x] build(deps): bump github/codeql-action in the ci group

internal/controller/receiver_controller.go
The `Mark…` functions in the `conditions` package accept a format string and (optional) arguments, just like `fmt.Printf` and friends.
In many places, the code passed an error message as the format string, causing it to be interpreted as a format string by the `fmt` package. This leads to issues when the message contains percent signs, e.g. URL-encoded values.
This PR adds a format string and shortens `err.Error()` to `err`, which yields the same output.
This change is identical in principle to fluxcd/source-controller#1529.
=> Fix incorrect use of format strings with the `conditions` package.

internal/notifier/telegram_test.go
The test would sometimes fail because the metadata lines are built from a map and map iteration order in Go is non-deterministic.  Therefore, the lines may be ordered differently between different test runs.
Now, the test sorts the metadata lines of the telegram message so they are always the same and only then verifies the expected output.
closes #867
=> Fix telegram test flake

internal/controller/receiver_controller_test.go, internal/server/event_server.go, internal/server/event_server_test.go, internal/server/receiver_server.go, main.go
Flag detailed-metrics added to provide a way to disable exposing all accessed paths to the metrics and  prevent potential metrics cardinality explosion
Issue ref: https://github.com/fluxcd/notification-controller/issues/828
=> New flag to disable detailed metrics for path

docs/spec/v1beta3/providers.md, internal/notifier/teams.go, internal/notifier/teams_test.go
Fixes #878 
The solution implemented in this PR for addressing the deprecation of the Office 365 Connector is checking the host of the address. If the suffix `.webhook.office.com` is present, the controller will keep the old behavior and send the existing payload format. Otherwise, a new payload format for Microsoft Adaptive Card will be sent, which is compatible with the new solution offered by Microsoft Teams: [Incoming Webhook with Workflows](https://support.microsoft.com/en-us/office/create-incoming-webhooks-with-workflows-for-microsoft-teams-8ae491c7-0394-4861-ba59-055e33f75498).
=> Add MS Adaptive Card payload to `msteams` Provider

go.mod, go.sum, internal/notifier/gitlab.go
go-gitlab moves to gitlab.com: https://github.com/xanzy/go-gitlab/issues/2060. The latest releases of https://gitlab.com/gitlab-org/api/client-go require Go 1.23.4, and I don't want to do a Go upgrade into this PR.
=> Migrate to `gitlab.com/gitlab-org/api/client-go`

internal/notifier/teams.go, internal/notifier/teams_test.go
In teams notifications, configure the adaptive card to expand and make full use of extra canvas space by setting the `msteams.width` property to `Full` (https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cdesktop1%2Cdesktop2%2Cconnector-html#full-width-adaptive-card).
This allow the card to be wider and more similar to the legacy message card version.
This is an implementation of the point 1 in https://github.com/fluxcd/notification-controller/issues/956.
Before:
After:
=> msteams notifier: adaptive cards full width

docs/spec/v1beta3/providers.md, internal/notifier/alertmanager.go, internal/notifier/alertmanager_fuzz_test.go, internal/notifier/alertmanager_test.go, internal/notifier/factory.go
I'm not a programmer, but after examining the other providers, i think this should be correct. Please let me know :)
Closes: #1020
=> Add support for Bearer Token authentication to Provider `alertmanager`

internal/notifier/gitlab.go
The get commit-status request is paginated and only returns the first 20 commit statuses by default. This change fetches the commit-status by name to avoid multiple requests.
RESOLVES #1009
=> fix: adding of duplicate commit statuses in gitlab

api/v1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/api/v1/notification.md, docs/spec/v1/receivers.md, go.mod, go.sum, internal/controller/receiver_controller.go, internal/controller/receiver_controller_test.go, internal/server/receiver_handler_test.go, internal/server/receiver_handlers.go, internal/server/receiver_resource_filter.go, internal/server/receiver_resource_filter_test.go, internal/server/receiver_server.go
This implementation allows filtering of wildcarded resources for receivers using CEL expressions.
Closes: https://github.com/fluxcd/notification-controller/issues/491
Spec: https://github.com/fluxcd/notification-controller/issues/491#issuecomment-2404615301
=> Implement Receiver resource filtering with CEL

docs/spec/v1beta3/providers.md
The currrent gitlab v4 API does no longer accept a project name for setting git commit status, a project ID must be used.
This PR adds an explanation and example for that to the provider docs and also clarifies the scope for the access token.
=> Clarify gitlab notification provider usage

docs/spec/v1beta1/providers.md, docs/spec/v1beta2/providers.md, docs/spec/v1beta3/providers.md
Current documentation does not mention that Telegram provider supports Telegram forum chats' topics, which it does, since [the shoutrrr lib does](https://github.com/containrrr/shoutrrr/pull/362/files). Therefore, no changes are needed in the FluxCD Notification Controller in order to send Telegram alerts to said topics.
This PR contains documentation changes that describe how you can set Telegram provider up to work with Telegram forum chats.
Closes [#1063](https://github.com/fluxcd/notification-controller/issues/1063)
=> Update docs to include Telegram forum configuration

internal/notifier/gitea.go, internal/notifier/gitea_test.go
It is required when a custom CA is passed, otherwise the gitea.NewClient() call will fail with the 'tls: failed to verify certificate: x509: certificate signed by unknown authority' error. Because the current version of Gitea SDK performs a call to the '/api/v1/version' endpoint during a new client creation, so the 'certPool' must be passed when creating the client.
Resolves: #1083
=> fix: pass 'certPool' to Gitea client on creation

go.mod, go.sum, internal/notifier/factory.go, internal/notifier/gitea.go, internal/notifier/gitea_test.go, tests/listener/listener.go, tests/proxy/proxy.go
As was mentioned [here](https://github.com/fluxcd/notification-controller/pull/1084#pullrequestreview-2709351090) we're missing the proxy setting for Gitea. This PR introduces support for Gitea 'proxyURL'.
=> feat: add 'proxyURL' support to Gitea notifier

docs/spec/v1beta3/providers.md
Part of: https://github.com/fluxcd/flux2/issues/5022
=> [RFC-0010] Link workload identity docs to complete guide

api/v1/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml
CrossNamespaceObjectReference should limit reference names to 253, which is the limit for `.metadata.name` and `.metadata.namespace`, ref https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
=> CrossNamespaceObjectReference: Fix MaxLength validation to k8s max 253 char

docs/spec/v1beta3/providers.md, go.mod, go.sum, internal/notifier/factory.go, internal/notifier/telegram.go, internal/notifier/telegram_test.go
Add proxy support to Telegram notifier by replacing shoutrrr with direct Telegram Bot API calls.
- Replace shoutrrr.Send with postMessage function for proxy support
- Add ProxyURL field to Telegram struct
- Update v1beta3 documentation to remove proxy limitation
Proxy functionality should work with ProxySecretRef added in #1133. Implementation follows existing patterns and should work in theory, but only verified through unit tests as I don't have a Telegram test environment.
Since this implementation uses the existing postMessage function for proxy handling, no additional proxy-specific tests were added.
Resolves #432
=> Add proxy support to Telegram notifier

internal/server/event_handlers.go
This PR fixes a performance regression introduced in #1139 where `spec.secretRef` was being fetched twice.
As pointed out by @matheuscscp in https://github.com/fluxcd/notification-controller/pull/1139#issuecomment-3056595416, the implementation was fetching the secret twice:
1. Once in `extractAuthFromSecret`
2. Again in `secrets.BasicAuthFromSecret`
Since notification-controller doesn't cache secrets by default, this has a significant performance impact.
Following Option 1 from https://github.com/fluxcd/flux2/issues/5433#issuecomment-3031563739, this PR moves the BasicAuth processing directly into `extractAuthFromSecret` using the already-fetched secret data. This aligns with the special nature of `spec.secretRef` that contains multiple authentication methods.
=> Fix double secret fetching in BasicAuth processing
