Makefile, api/v1alpha1/alert_types.go, api/v1alpha1/doc.go, config/crd/bases/notification.fluxcd.io_alerts.yaml, docs/api/notification.md, docs/spec/README.md, go.mod, hack/api-docs/config.json, hack/api-docs/template/members.tpl, hack/api-docs/template/pkg.tpl, hack/api-docs/template/type.tpl, internal/notifier/client.go, internal/server/handlers.go
Changes:
- Retry alert HTTP POST four times with an exponential backoff of maximum 30 seconds
- Add delivery method to specs
- Generate API documentation
=> Implement retry with backoff for alert posting

config/samples/notification_v1alpha1_alert.yaml, docs/spec/README.md, docs/spec/v1alpha1/alert.md, docs/spec/v1alpha1/provider.md, internal/server/handlers.go
Allow an alert to target all resources of a particular kind in a namespace using `*` as resource name.
=> Add wildcard support

go.mod, go.sum, internal/server/receiver_handlers.go
Changes:
- Update source-controller to v0.0.5
- Use `fluxcd.io/reconcileAt` annotation
=> Update source-controller to v0.0.5

internal/server/event_handlers.go
Changes:
- Lookup alerts at cluster level
- Include involved object kind in logs
=> Lookup alerts at cluster level

controllers/alert_controller.go, controllers/provider_controller.go, controllers/receiver_controller.go
Change structure logging labels to match the controller runtime format
Ref: https://github.com/fluxcd/toolkit/issues/94
=> Normalise controller logs

docs/spec/v1alpha1/alert.md
Quick typo fix to align the the docs with the API reference.
=> Change ObjectReference to LocalObjectReference

api/v1alpha1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1alpha1/provider.md, go.mod, internal/notifier/camelcase.go, internal/notifier/factory.go, internal/notifier/github.go, internal/notifier/github_test.go, internal/server/event_handlers.go
=> Implement GitHub commit status notifier

api/v1alpha1/reference_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/v1alpha1/alert.md, docs/spec/v1alpha1/receiver.md, go.mod, go.sum, internal/server/receiver_handlers.go
Ref: https://github.com/fluxcd/toolkit/discussions/242
=> Add support for S3 buckets to alerts and receivers

.github/workflows/e2e.yaml, .github/workflows/fossa.yml, .github/workflows/release.yml, Makefile, README.md, docs/internal/release.md, docs/spec/README.md, docs/spec/v1beta1/alert.md, docs/spec/v1beta1/provider.md, docs/spec/v1beta1/receiver.md
Changes:
- Set `main` as default branch
- Remove  `gitops-system` namespace refs
Ref: https://github.com/fluxcd/toolkit/issues/152
=> Update default branch and namespace

controllers/alert_controller.go, controllers/provider_controller.go, controllers/receiver_controller.go, go.mod, go.sum, main.go
This PRs adds Prometheus instrumentation for the source reconciliation duration and ready status.
Ref: https://github.com/fluxcd/toolkit/issues/329
=> Implement Prometheus instrumentation

docs/spec/v1beta1/alert.md, docs/spec/v1beta1/event.md, docs/spec/v1beta1/provider.md, docs/spec/v1beta1/receiver.md
Ref: https://github.com/fluxcd/toolkit/issues/319
=> Add namespace to API docs examples

api/go.mod, api/go.sum, go.mod, go.sum, internal/server/receiver_handlers.go
Changes:
- update `fluxcd/pkg/apis/meta` to v0.1.0
- update `fluxcd/pkg/runtime` to v0.1.2
- trigger reconciliation with `reconcile.fluxcd.io/requestedAt` annotation
Ref: https://github.com/fluxcd/pkg/issues/39
=> Use reconcile request annotation

CHANGELOG.md, Makefile, README.md, config/manager/kustomization.yaml, go.mod, go.sum
Ref: https://github.com/fluxcd/toolkit/issues/388
=> Release v0.2.0

docs/spec/v1beta1/receiver.md
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
=> Fix Receiver apiVersion in spec

docs/api/notification.md, hack/api-docs/template/pkg.tpl
Signed-off-by: Gert Dewit <gert@hobbiton.be>
=> Fix "Notification API reference" title

config/manager/deployment.yaml, go.mod, go.sum, main.go
Add readiness/liveness probes using controller-runtime helpers.
=> Add readiness/liveness probes

internal/notifier/github.go, internal/notifier/github_test.go
=> Add check for duplicate status to avoid spamming the same status

internal/server/receiver_handlers.go
Lookup receivers in all namespaces filtered by readiness status.
Fix: #95
=> Lookup ready receivers in all namespaces

api/v1beta1/alert_types.go, api/v1beta1/provider_types.go, api/v1beta1/receiver_types.go
=> Add kinds to api types

api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
=> Add ACR webhook receiver

api/v1beta1/provider_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, docs/spec/v1beta1/provider.md, internal/notifier/factory.go, internal/notifier/webex.go, internal/notifier/webex_test.go
=> Add support for Webex as an alert provider

api/v1beta1/alert_types.go, api/v1beta1/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, controllers/alert_controller.go, controllers/provider_controller.go, controllers/receiver_controller.go, docs/api/notification.md
=> Add observedGeneration to status of alert and receivers

internal/notifier/telegram.go
=> Escape metadata string for Telegram notification

internal/notifier/gitlab.go
Closes #212 
This pull request checks for duplicate Gitlab status and does post a status if one is found.
=> Gitlab retried job

docs/spec/v1beta1/provider.md, docs/spec/v1beta1/receiver.md
=> Bitbucket docs

internal/notifier/webex.go
=> Use x509 certificate for Webex

docs/spec/v1beta1/provider.md
=> Update docs for telegram

.github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yml, .github/workflows/scan.yml, .goreleaser.yaml
This PR implements:
- https://github.com/fluxcd/flux2/issues/2302
- https://github.com/fluxcd/flux2/issues/2303
=> Publish SBOM and sign release artifacts

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
=> Release v0.22.0

controllers/provider_controller.go, docs/spec/v1beta1/provider.md, internal/server/event_handlers.go
Signed-off-by: Filipe Sequeira <filipe@weave.works>
=> Allow the proxy address to specified in the Kubernetes Secret from Alert `spec.secretRef`

internal/server/event_handlers.go
Filter events metadata based on the involved object group.
=> Filter event metadata based on the object group

README.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update toolkit.fluxcd.io docs link

internal/notifier/bitbucket.go
This pull request checks if a similar commit status has been sent to the BitBucket API to avoid spamming. 
This feature is already implemented for the other git providers.
=> Check for duplicate commit status in Bitbucket

docs/spec/v1beta1/provider.md
Adds documentation for setting up notification for Microsoft teams.
Fix: https://github.com/fluxcd/website/issues/738
=> Add docs for Microsoft Teams

docs/spec/v1beta1/receiver.md, internal/server/receiver_handlers.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
=> Update flux types api versions

go.mod, go.sum, internal/notifier/azure_devops.go, internal/notifier/azure_devops_test.go
Updates the Azure DevOps API to the latest version. No real feature changes, just keeping things up to date.
Signed-off-by: Philip Laine <philip.laine@gmail.com>
=> Update Azure DevOps Go API

docs/spec/v1beta1/provider.md
Fixes: fluxcd/website#1057
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> Add missing language to fenced code block

controllers/alert_controller.go, controllers/provider_controller.go, controllers/receiver_controller.go
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Implements RecoverPanic option on reconcilers.
part of [issue #2952](https://github.com/fluxcd/flux2/issues/2952#issue-1325576799)
=> Enables RecoverPanic option on reconcilers

DEVELOPMENT.md, README.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update to new doc links structure

api/v1beta1/condition_types.go, controllers/alert_controller.go, controllers/provider_controller.go, controllers/receiver_controller.go
=> Add finalizers to the custom resources

Dockerfile
=> Dockerfile: Build with Go 1.19

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Ref: https://github.com/fluxcd/flux2/issues/3228
=> Release v0.28.0

api/v1beta2/provider_types.go, api/v1beta2/receiver_types.go, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, controllers/provider_controller_test.go, controllers/receiver_controller_test.go
Fix: https://github.com/fluxcd/flux2/discussions/3434
Followup: https://github.com/fluxcd/notification-controller/pull/455
=> Remove interval default value from CRDs

.github/workflows/release.yml
Ref: https://github.com/fluxcd/flux2/issues/3522
=> build: Enable SBOM and SLSA Provenance

.github/workflows/release.yml, .github/workflows/scan.yml
Part of https://github.com/fluxcd/flux2/issues/3663
=> build: update release workflow

docs/spec/v1beta2/receivers.md
=> fixes to the Receiver documentation

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/3842
=> Release v1.0.0-rc.2

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/3881
=> Release v1.0.0-rc.3

.github/workflows/backport.yaml, .github/workflows/release.yml
Partial backport of #573 
Full backport of #574
=> [release/v1.0.x] Manual backport of CI fixes

docs/spec/v1beta2/providers.md
=> change key type to []byte in provider spec docs

docs/spec/v1beta2/providers.md
=> Clarify permission requirements for Gitea provider token

internal/notifier/rocket.go, internal/notifier/rocket_test.go
=> Remove checks for empty user and channel parameters in Rocket notifier

internal/notifier/bitbucketserver.go
=> Fix BitBucket status update panic

internal/server/event_handlers.go
=> Sanitize provider data loaded from secret

internal/notifier/factory.go
=> Use `password` as fallback for the Git provider `token` auth

docs/spec/v1beta3/providers.md
=> docs: use `stringData` for secret of GitHub PAT

Makefile, config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml, config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml, config/crd/bases/notification.toolkit.fluxcd.io_receivers.yaml, config/rbac/role.yaml
Part of: https://github.com/fluxcd/flux2/issues/4947
=> Update controller-gen to v0.16.1

go.mod, go.sum, internal/notifier/azure_devops.go, internal/notifier/azure_devops_test.go, internal/notifier/bitbucket.go, internal/notifier/bitbucketserver.go, internal/notifier/bitbucketserver_test.go, internal/notifier/gitea.go, internal/notifier/gitea_test.go, internal/notifier/github.go, internal/notifier/gitlab.go, internal/server/event_server.go, internal/server/event_server_test.go
Part of: https://github.com/fluxcd/flux2/issues/5148
=> Add support for MetaOriginRevisionKey from the Event API

docs/spec/v1beta3/providers.md
Part of: https://github.com/fluxcd/flux2/issues/5148
=> Add subsection for Git providers supporting commit status updates

go.mod, internal/server/receiver_handler_test.go, internal/server/receiver_handlers.go
* Log a specific error when the payload exceeds the maximum size
* Fixes GitHub payload extraction logic
=> Improvements after CEL resource filtering

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of https://github.com/fluxcd/flux2/issues/5186
=> Release v1.5.0

internal/server/event_handlers.go
Log only the Secret name with invalid proxy settings.
=> Sanitize proxy error logging

.github/labels.yaml
Part of: https://github.com/fluxcd/flux2/issues/5363
=> Add 1.6.x release label

.github/dependabot.yaml
Part of: https://github.com/fluxcd/flux2/issues/5372
=> Update dependabot config

go.mod, go.sum, internal/server/event_handlers.go
ref: https://github.com/fluxcd/flux2/issues/5433#issuecomment-3092380180.
=> Fix missing TLS ServerName in Provider notifications

docs/spec/v1beta3/providers.md, internal/notifier/alertmanager.go, internal/notifier/alertmanager_fuzz_test.go, internal/notifier/alertmanager_test.go, internal/notifier/factory.go
=> Introduce proper basic auth support for Alertmanager Provider

go.mod, go.sum, internal/server/event_handlers.go
ref: https://github.com/fluxcd/pkg/pull/1007, https://github.com/fluxcd/pkg/pull/993
=> Remove TLS ServerName pinning in TLS config creation

go.mod, go.sum, internal/notifier/azure_helpers.go, internal/notifier/google_helpers.go, internal/server/event_handlers_test.go, main.go
Part of: https://github.com/fluxcd/flux2/issues/5465
=> [RFC-0010] Add default-service-account for lockdown

.github/workflows/backport.yaml, .github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yml, .github/workflows/scan.yml, .github/workflows/sync-labels.yaml
Part of: https://github.com/fluxcd/flux2/issues/5523
=> ci: Refactor CI with `fluxcd/gha-workflows`

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/5516
=> Release v1.7.1

CHANGELOG.md
(cherry picked from commit f92a3e28effa1ad470f7d6c3ced77a373995d3fa)
=> Add changelog entry for v1.7.3
